version: '3'
services:
  zmk-build:
    build: .
    volumes:
      - .:/app
      - zmk-root:/app/zmk
      - zmk-build:/app/build
    environment:
      - ZEPHYR_BASE=/app/zephyr
      - GNUARMEMB_TOOLCHAIN_PATH=/usr/local/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi

volumes:
  zmk-root:
  zmk-build:
